#!/usr/bin/env bash
#
# Builds what the framework's plugins can't keep by hand. The plugins in plugins/ are the source of the
# framework's machinery (decision 0028): their skills, agents, workflows, hooks, and reference docs are
# written in the form a packaged project loads, and scripts/build-committed.py writes a committed
# project's copies from them. Three things are generated:
#
# - In every plugin's bin/, the commands its modules list in module.json (decision 0027):
#   parallel-agents' scripts/agent/worktree-new.sh becomes adf's adf-worktree-new, on the Bash tool's
#   PATH while the plugin is on. A module's scripts stay in the module, which a committed install copies.
#   Each command carries the helper its script loads, finds the project from the working directory, and
#   runs the project's own script instead when a committed install has one.
# - The spec model in adf's workflows: Claude Code doesn't fill in ${CLAUDE_PLUGIN_ROOT} in a workflow
#   script, so the line `const SPEC_MODEL = "…"` carries docs/SPEC-MODEL.md's text, kept equal here.
# - Every plugin's version, which is adf's: a release sets it by hand (decision 0017), and this script
#   copies it into the others' manifests (decision 0023).
#
# Each plugin's .generated file lists the paths this script owns; never edit those. Change the module's
# script, the doc, or adf's version, and run this again; evals/static/check-skills.sh fails when a
# plugin and its sources drift apart.
#
# Usage: scripts/build-plugins.sh [output root — default: this repository]
#   Rewrites <root>/plugins/<plugin>/'s generated parts; <root>/plugins/ must hold the plugins' sources
#   (the drift check builds a copy). The modules are always this repository's.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_ROOT="${1:-$ROOT}"

python3 - "$ROOT" "$OUT_ROOT" <<'PY'
import json, os, re, shutil, sys

root, out_root = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(root, "scripts"))
from forms import CORE, SPEC_MODEL_TEXT, Machinery

machinery = Machinery(out_root, modules_root=root)  # the plugins being built, with this repository's modules

# A command is its module's script in one file, with the helper the script loads inlined, so it loads
# nothing by a path the shell computes (the Claude Directory refuses those for hooks). The helper's one
# self-locating line, which a committed script uses to find the project, points at the same folder in
# the project instead, found from the working directory: the Bash tool sets neither CLAUDE_PLUGIN_ROOT
# nor CLAUDE_PROJECT_DIR (decision 0027, finding 4).
LOAD_HELPER = re.compile(r'^\. "\$\(dirname "\$0"\)/(_[\w-]+\.sh)"$', re.M)
SELF_DIR = re.compile(r'^(\w+)="\$\(cd "\$\(dirname "\$\{BASH_SOURCE\[0\]\}"\)" && pwd\)"$', re.M)
COMMAND_HEAD = """#!/usr/bin/env bash
# {name}: the {plugin} plugin's copy of the {module} module's {rel},
# on the Bash tool's PATH while the plugin is on (decision 0027).
# Generated by scripts/build-plugins.sh: change the module's script and build again.
if ! ADF_CHECKOUT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "Error: not inside a git repository." >&2
  exit 1
fi
# A project without the module has no {folder}/: in a packaged install it keeps the module's settings.
if [ ! -d "$ADF_CHECKOUT/{folder}" ]; then
  echo "Error: this project doesn't use the {module} module (no {folder}/)." >&2
  exit 1
fi
# A committed install keeps the module's script: run that, the version this project upgraded to.
if [ -x "$ADF_CHECKOUT/{rel}" ]; then
  exec "$ADF_CHECKOUT/{rel}" "$@"
fi

"""


def write_commands(plugin, out):
    commands = {n: r for n, r in machinery.command_script.items() if machinery.module_plugin[machinery.command_module[n]] == plugin}
    for name, rel in sorted(commands.items()):
        module = machinery.command_module[name]
        path = os.path.join(root, "modules", module, "files", rel)
        folder = os.path.dirname(rel)
        with open(path, encoding="utf-8") as f:
            text = f.read()
        shebang, _, body = text.partition("\n")
        assert shebang == "#!/usr/bin/env bash", f"{rel} doesn't start with #!/usr/bin/env bash"

        def inline(m):
            with open(os.path.join(os.path.dirname(path), m.group(1)), encoding="utf-8") as f:
                helper = f.read()
            assert len(SELF_DIR.findall(helper)) == 1, f"{m.group(1)} doesn't find its folder the way the build rewrites"
            helper = SELF_DIR.sub(lambda d: f'{d.group(1)}="$ADF_CHECKOUT/{folder}"', helper)
            helper = re.sub(r"\A(#.*\n)+\n*", "", helper)  # its header says it's sourced, never run
            return f"# ── {m.group(1)}, inlined ──\n{helper.rstrip()}\n# ── end of {m.group(1)} ──"

        body = LOAD_HELPER.sub(inline, body)
        assert 'dirname "$0"' not in body and "BASH_SOURCE" not in body, \
            f"{rel} finds a file beside itself, which a command can't: load it the way the build inlines"
        target = os.path.join(out, "bin", name)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        head = COMMAND_HEAD.format(name=name, plugin=plugin, rel=rel, module=module, folder=folder)
        with open(target, "w", encoding="utf-8") as f:
            f.write(head + machinery.to_plugin_names(body))
        os.chmod(target, 0o755)
    return ["bin"] if commands else []


def build(plugin):
    out = os.path.join(out_root, "plugins", plugin)
    listing = os.path.join(out, ".generated")
    # Only bin/ is ever generated whole; anything else listed is a source a build must never delete.
    old = open(listing, encoding="utf-8").read().split() if os.path.exists(listing) else []
    assert set(old) <= {"bin"}, f"plugins/{plugin}/.generated lists {sorted(set(old) - {'bin'})}, which are sources now (decision 0028)"
    shutil.rmtree(os.path.join(out, "bin"), ignore_errors=True)
    generated = write_commands(plugin, out)
    with open(listing, "w", encoding="utf-8") as f:
        f.write("".join(f"{rel}\n" for rel in generated))
    return generated


# ─── adf ───────────────────────────────────────────────────────────────

build(CORE)
spec_model = machinery.spec_model()
for name in machinery.workflows:
    path = machinery.path("workflows", name + ".js")
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if SPEC_MODEL_TEXT.search(text):
        with open(path, "w", encoding="utf-8") as f:
            f.write(SPEC_MODEL_TEXT.sub(lambda m: spec_model, text))
print(f"plugins/{CORE}: {len(machinery.command_script)} commands from modules; the spec model in its workflows")

# ─── The other plugins (decision 0023) ────────────────────────────────────────

with open(os.path.join(out_root, "plugins", CORE, ".claude-plugin", "plugin.json"), encoding="utf-8") as f:
    version = json.load(f)["version"]
for plugin in machinery.plugins:
    if plugin == CORE:
        continue
    build(plugin)
    # One release, one version: adf's, which a release sets by hand.
    path = os.path.join(out_root, "plugins", plugin, ".claude-plugin", "plugin.json")
    with open(path, encoding="utf-8") as f:
        manifest = json.load(f)
    assert manifest.get("name") == plugin, f"plugins/{plugin}/.claude-plugin/plugin.json: the name must be {plugin}"
    manifest["version"] = version
    with open(path, "w", encoding="utf-8") as f:
        f.write(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
print(f"{len(machinery.plugins) - 1} other plugin(s) at adf's version, {version}")
PY
